# Generated by Django 4.2.3 on 2023-08-24 14:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_role_alter_organization_options'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='organizationjoinrequest',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='organizationjoinrequest',
            name='org',
        ),
        migrations.RemoveField(
            model_name='organizationjoinrequest',
            name='user',
        ),
        migrations.DeleteModel(
            name='Role',
        ),
        migrations.RemoveField(
            model_name='todouser',
            name='admin_org',
        ),
        migrations.RemoveField(
            model_name='todouser',
            name='organization',
        ),
        migrations.DeleteModel(
            name='Organization',
        ),
        migrations.DeleteModel(
            name='OrganizationJoinRequest',
        ),
    ]
