version: '3'

services:
  todo:
    build: .
    container_name: todo
    image: todo:1.1
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - db

#  todo_db:
#    image: postgres:latest
#    environment:
#      - POSTGRES_HOST_AUTH_METHOD=${POSTGRES_HOST_AUTH_METHOD}
#    volumes:
#      - todo_postgres_data:/var/lib/todo_postgres_data/data/

  db:

    image: postgres:latest
    environment:
      - POSTGRES_USER=${DASHBOARD_POSTGRES_USER}
      - POSTGRES_PASSWORD=${DASHBOARD_POSTGRES_PASSWORD}
      - POSTGRES_DB=${DASHBOARD_POSTGRES_DB} #optional (specify default database instead of $POSTGRES_DB)
    ports:
      - "5432:5432"
    restart: always
    volumes:
      - postgres_vol:/var/lib/postgres/data/
  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4:latest
    environment:
        - PGADMIN_DEFAULT_EMAIL=${PGADMIN_MAIL}
        - PGADMIN_DEFAULT_PASSWORD=${PGADMIN_PW}
    ports:
      - "5050:80"
    restart: always

volumes:
  postgres_vol: