# Generated by Django 4.2.3 on 2023-09-13 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todos', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='task',
            options={'permissions': [('can_be_assigned', 'Can Be Assigned to User')]},
        ),
        migrations.AddField(
            model_name='task',
            name='priority',
            field=models.CharField(choices=[('1', 'TOP'), ('2', 'MID'), ('3', 'LOW')], default='LOW', max_length=3),
        ),
    ]
