# Generated by Django 4.2.3 on 2023-09-23 02:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todos', '0004_task_active'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='task',
            options={'ordering': ['due_date'], 'permissions': [('can_be_assigned', 'Can Be Assigned to User')]},
        ),
    ]
